import type { MealEntry as Meal } from '../types/meal.js';
import { displayDate, escapeHtml } from '../utils/html.js';

const tags = [
  ['HIGH_FAT_OR_FRIED', 'Higher fat or fried'], ['VERY_HIGH_FIBER', 'Very high fiber'],
  ['VERY_HIGH_SUGAR', 'Very high sugar'], ['SPICY', 'Spicy'], ['ALCOHOL', 'Alcohol'], ['CAFFEINE', 'Caffeine'],
];
const amount = (value: number | null | undefined) => value == null ? '' : String(Math.round(value * 10) / 10);
const metric = (label: string, value: number | null | undefined, unit: string) => `<div class="nutrition-metric"><small>${label}</small><b>${value == null ? 'Unknown' : `${amount(value)} ${unit}`}</b></div>`;

export function MealEntry(meal: Meal, editable = true): string {
  const values = meal.final_nutrition || meal.nutrition_estimate;
  const pending = Boolean(editable && values && !meal.patient_confirmed);
  const status = meal.analysis_status === 'UNCERTAIN' ? 'Marked uncertain' : meal.patient_confirmed ? 'Patient confirmed' : values ? 'Awaiting confirmation' : 'Patient reported';
  const estimate = values ? `<div class="nutrition-estimates">${metric('Energy', values.calories_kcal, 'kcal')}${metric('Protein', values.protein_g, 'g')}${metric('Carbohydrates', values.carbohydrates_g, 'g')}${metric('Fat', values.fat_g, 'g')}${metric('Portion', meal.estimated_portion_grams ?? values.estimated_portion_grams, 'g')}</div><p class="muted">Image-level estimate. Food names and recognition confidence are not provided by this model.</p>` : '<p class="muted">Nutrition estimate unavailable for this meal.</p>';
  const contexts = (meal.nutrition_context_flags || []).map(flag => `<div class="nutrition-context"><b>${escapeHtml(flag.level)} context</b><p>${escapeHtml(flag.message)}</p></div>`).join('');
  const provenance = values ? `<details class="nutrition-provenance"><summary>Estimate source</summary><small>${escapeHtml(meal.food_provider || 'Unknown')} · ${escapeHtml(meal.food_model_version || 'model version unavailable')}<br>${escapeHtml(meal.nutrition_estimation_method || 'method unavailable')}<br>Nutrition source: ${escapeHtml(meal.nutrition_source || 'Unknown')}<br>Recognition confidence: ${meal.recognition_confidence == null ? 'Not provided' : amount(meal.recognition_confidence)}</small></details>` : '';
  const correctionForm = editable && values ? `<form class="meal-confirm-form" data-meal-id="${escapeHtml(meal.id)}" data-confirmed="${meal.patient_confirmed}"><label>Meal description<input name="description" required maxlength="2000" value="${escapeHtml(meal.description)}" placeholder="Describe the meal"></label><label>Food items you identify <span class="muted">(comma separated; FoodCNN does not detect labels)</span><input name="food_items" maxlength="2000" value="${escapeHtml((meal.food_items || []).join(', '))}" placeholder="Enter food names"></label><fieldset class="food-tags"><legend>Meal characteristics you want to record</legend>${tags.map(([value,label]) => `<label class="check"><input type="checkbox" name="food_context_tags" value="${value}" ${(meal.food_context_tags || []).includes(value) ? 'checked' : ''}> ${label}</label>`).join('')}</fieldset><div class="nutrition-edit-grid"><label>Estimated portion (g)<input name="estimated_portion_grams" type="number" min="1" max="10000" step="1" value="${amount(meal.estimated_portion_grams)}"></label><label>Calories (kcal)<input name="calories_kcal" type="number" min="0" step="0.1" value="${amount(values.calories_kcal)}"></label><label>Protein (g)<input name="protein_g" type="number" min="0" step="0.1" value="${amount(values.protein_g)}"></label><label>Carbohydrates (g)<input name="carbohydrates_g" type="number" min="0" step="0.1" value="${amount(values.carbohydrates_g)}"></label><label>Fat (g)<input name="fat_g" type="number" min="0" step="0.1" value="${amount(values.fat_g)}"></label></div><div class="actions"><button class="button primary" type="submit">${meal.patient_confirmed ? 'Save corrections' : 'Confirm meal and values'}</button>${!meal.patient_confirmed ? `<button class="button" type="button" data-action="uncertain-meal" data-meal-id="${escapeHtml(meal.id)}">Mark uncertain</button>` : ''}</div><p id="meal-error-${escapeHtml(meal.id)}" class="error hidden"></p></form>` : '';
  const foodNames = (meal.food_items || []).length ? `<p><b>Patient-entered foods:</b> ${escapeHtml((meal.food_items || []).join(', '))}</p>` : '';
  return `<article class="meal-entry"><div class="meal-entry-heading"><div><span class="eyebrow">${escapeHtml(displayDate(meal.recorded_at))}</span><h3>${escapeHtml(meal.description || 'Meal photo analysis')}</h3></div><span class="pill ${meal.patient_confirmed ? 'green' : pending ? 'amber' : 'blue'}">${status}</span></div>${foodNames}${estimate}${contexts}${correctionForm}${provenance}</article>`;
}
