import type { AIResult } from './assessment.js';
import type { MedicationConflict } from './medication.js';
export interface AccessRequest { patient_id: number; doctor_id: number; patient_name?: string | null; patient_email?: string | null; doctor_name?: string | null; doctor_email?: string | null; doctor_access_code?: string | null; status: 'PENDING' | 'ACTIVE' | 'DECLINED' | 'REVOKED'; created_at?: string | null }
export interface PatientIdentity { id: number; email: string | null; display_name?: string | null }
export interface CareProfile { patient_id: number; identity: PatientIdentity; active_doctors: Array<{ id: number; email: string; display_name?: string | null }>; latest_mri: MRIStudy | null; latest_assessment: (AIResult & { score_semantics?: string }) | null; longitudinal_summary: Record<string, unknown>; surveillance: Record<string, unknown>; medications: MedicationRecord[]; symptoms: Symptom[]; meals: { status: string; entries: MealEntry[] }; recent_clinician_notes: Record<string, unknown>; review_queue: Record<string, unknown> }
export interface MRIStudy { id: string; original_filename: string; modality: string; file_format: 'NIFTI' | 'NIFTI_GZ'; uploaded_at: string; study_date: string | null; status: string; error_message: string | null }
export interface MRIAnalysisResponse { mri_study: MRIStudy; assessment: AIResult }
export interface MRIStudySummary { id: string; study_date: string | null; uploaded_at: string; assessments: AIResult[]; measurements: Array<Record<string, unknown>> }
export interface Symptom { id: string; patient_id: number; created_by_user_id: number; symptom_type: string; severity: number | null; onset_date: string | null; recorded_at: string; duration: string | null; notes: string | null; status: string; source: string; review_status: string; reviewed_by_user_id: number | null; reviewed_at: string | null; review_note: string | null; updated_at: string }
export interface MealEntry { id: string; patient_id: number; description: string; patient_confirmed: boolean; recorded_at: string }
export interface SurveillancePlan { id: string; patient_user_id: number; created_by_user_id: number; target_follow_up_date: string; interval: number | null; interval_unit: string | null; reason: string; status: string; notes: string | null; last_reviewed_at: string | null; next_review_date: string | null; created_at: string }
export interface MedicationRecord { id: string; patient_id: number | null; source_document_id: string; source_type: string; extracted_fields: Record<string, unknown>; verified_fields: Record<string, unknown> | null; verification_status: string; medication_status: string; extraction_confidence: number | null; page: number | null; source_text: string | null; doctor_note: string | null; created_at: string; verified_at: string | null; conflicts: MedicationConflict[] }
export interface MedicalReport { id: string; document: { id: string; original_filename: string; extraction_status: string; verification_status: string; created_at: string }; fields: Record<string, { value: string | number | boolean | null; status: string; extraction_confidence: number | null }>; verified_fields: Record<string, unknown> | null }
